<?php

return [
    'provinsi' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    'balai' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    'pulau' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    'kabupaten' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    'kecamatan' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    'ruas_jalan' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    // 'drp' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    // 'kelas_jalan' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    // 'koridor' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    // 'ruas_jalan_kabupaten' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    'link_kecamatan' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    'inventarisasi_jalan' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    'kondisi_jalan' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    'koordinat_gps' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    // 'nilai_mca_ruas' => ['read', 'add', 'detail', 'update', 'delete', 'import', 'export'],
    'peta_kabupaten' => ['read', 'detail'],
    // 'peta_kecamatan' => ['read', 'detail'],
    'hak_akses' => ['read', 'add', 'detail', 'update', 'delete'],
    'user' => ['read', 'add', 'detail', 'update', 'delete'],
    'profile' => ['read', 'add','detail', 'update', 'delete'], 
    'import_export' => ['read', 'add', 'detail','update', 'delete', 'import', 'export'],
];
